# Generated by Django 3.1.7 on 2021-03-09 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(default='', max_length=100)),
                ('package_type', models.CharField(default='', max_length=50)),
                ('package_images', models.ImageField(default='', upload_to='home/pro_image')),
                ('package_categories', models.CharField(default='', max_length=50)),
                ('package_duration', models.IntegerField(default=0)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('package_created', models.DateField()),
                ('package_createdby', models.CharField(default='', max_length=50)),
                ('package_video', models.FileField(default='', upload_to='home/pro_image')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('passengers', models.IntegerField(default=0)),
                ('daya_tour', models.IntegerField(default=0)),
                ('date_tour', models.DateField()),
                ('enddate_tour', models.DateField()),
                ('order_status', models.CharField(default='', max_length=50)),
                ('date_ordered', models.DateField()),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='holidays.packages')),
            ],
        ),
    ]
