# Generated by Django 3.1.7 on 2021-03-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_city', models.CharField(default='', max_length=50)),
                ('hotel_country', models.CharField(default='', max_length=100)),
                ('hotel_name', models.CharField(default='', max_length=50)),
                ('hotel_image', models.ImageField(default='', upload_to='home/pro_image')),
                ('hotels_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hotel_createdby', models.CharField(default='', max_length=50)),
                ('hotel_no_of_rooms', models.IntegerField(default=0)),
                ('hotel_type_room', models.CharField(default='', max_length=20)),
                ('hotel_datecreated', models.DateField()),
                ('hotel_updatedon', models.DateField()),
            ],
        ),
    ]
