# Generated by Django 3.1.7 on 2021-03-09 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_hotels'),
    ]

    operations = [
        migrations.CreateModel(
            name='transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_mode', models.CharField(default='', max_length=50)),
                ('service_name', models.CharField(default='', max_length=100)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('added_by', models.CharField(default='', max_length=50)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 3, 9, 7, 55, 52, 796660, tzinfo=utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='hotel_datecreated',
        ),
        migrations.AddField(
            model_name='hotels',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 13, 25, 52, 795611)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_updatedon',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 7, 55, 52, 795611, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 7, 55, 52, 794612, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 7, 55, 52, 793626, tzinfo=utc)),
        ),
    ]
