# Generated by Django 3.1.7 on 2021-03-09 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0005_auto_20210309_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hotel_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hotels',
            name='hotel_services',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='packages',
            name='package_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='packages',
            name='package_drop',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='packages',
            name='package_food',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='packages',
            name='package_hotels',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='packages',
            name='package_pickup',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='packages',
            name='package_restaurant',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='packages',
            name='package_services',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 15, 7, 20, 491391)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_updatedon',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 9, 37, 20, 491391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 9, 37, 20, 491391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_tour',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='enddate_tour',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 9, 37, 20, 491391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transport',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 9, 37, 20, 491391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 9, 37, 20, 491391, tzinfo=utc)),
        ),
    ]
