# Generated by Django 3.1.7 on 2021-03-10 05:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0006_auto_20210309_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 10, 44, 55, 194779)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_updatedon',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 5, 14, 55, 194779, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotels_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 5, 14, 55, 194779, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 5, 14, 55, 193752, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transport',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 5, 14, 55, 194779, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 5, 14, 55, 194779, tzinfo=utc)),
        ),
    ]
